// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjw1uhPtS3AsgwiVuXL-nap2s1Iro-yeI',
    appId: '1:364803740118:web:813b9e21aba213635b9477',
    messagingSenderId: '364803740118',
    projectId: 'jokes-project-lab',
    authDomain: 'jokes-project-lab.firebaseapp.com',
    storageBucket: 'jokes-project-lab.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDycnTvBSmKul0ScARJAbDQOfQOI54UZ1k',
    appId: '1:364803740118:android:7605c2ffb87b2f7a5b9477',
    messagingSenderId: '364803740118',
    projectId: 'jokes-project-lab',
    storageBucket: 'jokes-project-lab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB7PvtqBj6OI-6scE_mNc_FKJp16NYdayg',
    appId: '1:364803740118:ios:75c766351004e9675b9477',
    messagingSenderId: '364803740118',
    projectId: 'jokes-project-lab',
    storageBucket: 'jokes-project-lab.firebasestorage.app',
    iosBundleId: 'com.example.lab2213094',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB7PvtqBj6OI-6scE_mNc_FKJp16NYdayg',
    appId: '1:364803740118:ios:75c766351004e9675b9477',
    messagingSenderId: '364803740118',
    projectId: 'jokes-project-lab',
    storageBucket: 'jokes-project-lab.firebasestorage.app',
    iosBundleId: 'com.example.lab2213094',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjw1uhPtS3AsgwiVuXL-nap2s1Iro-yeI',
    appId: '1:364803740118:web:360318396dbc56fb5b9477',
    messagingSenderId: '364803740118',
    projectId: 'jokes-project-lab',
    authDomain: 'jokes-project-lab.firebaseapp.com',
    storageBucket: 'jokes-project-lab.firebasestorage.app',
  );

}